name: Weekly JSON Update

on:
  schedule:
    - cron: '0 8 * * 5' # Runs every Friday midnight (PST)
  workflow_dispatch: 

jobs:
  merge:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set year-based variables
        run: |
          echo "CURRENT_YEAR=$(date +%Y)" >> $GITHUB_ENV
          echo "MERGED_FILE_NAME=searchEditions$(date +%Y).json" >> $GITHUB_ENV

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate Signature and Execute GraphQL Request
        env:
          SECRET: ${{ secrets.SECRET }}
        run: |
          CORRELATION_ID=$(uuidgen)
          TRACE_ID=$(uuidgen)
          TIMESTAMP=$(date +%s%3N)

          VERSION_NAME="4.97.0"
          VERSION_CODE="4734785"

          MESSAGE="${CORRELATION_ID}:${TIMESTAMP}"

          SIGNATURE=$(
            echo -n "$MESSAGE" |
            openssl dgst -sha256 -hmac "$SECRET" -binary |
            base64 -w 0
          )

          echo "CORRELATION_ID=$CORRELATION_ID" >> "$GITHUB_ENV"
          echo "TRACE_ID=$TRACE_ID" >> "$GITHUB_ENV"
          echo "TIMESTAMP=$TIMESTAMP" >> "$GITHUB_ENV"
          echo "SIGNATURE=$SIGNATURE" >> "$GITHUB_ENV"
          echo "VERSION_NAME=$VERSION_NAME" >> "$GITHUB_ENV"
          echo "VERSION_CODE=$VERSION_CODE" >> "$GITHUB_ENV"

      - name: Download new json
        env:
          ENDPOINT: ${{ secrets.GRAPHQL_URL }}
        run: |
          HTTP_CODE=$(curl -sSL -G \
            "$ENDPOINT" \
            --data-urlencode "operationName=SearchEditions" \
            --data-urlencode 'variables={"pagingInfo":{"pageSize":24,"pageNumber":1,"pagingType":"OFFSET"},"searchParams":{"editionType":["WEEKLY"],"countryCode":"US"}}' \
            --data-urlencode 'query=query SearchEditions($pagingInfo: PaginationArguments!, $searchParams: SearchEditionFilter) { searchEditions(pagingInfo: $pagingInfo, searchParams: $searchParams) { edges { node { id tegId editionType issueDate headline flyTitle rubric datePublished cover { __typename ...EditionCoverFragment } } } } } fragment EditionCoverFragment on ImageComponent { sourceId url altText type dateModified width height credit }' \
            -H "x-teg-signature: $SIGNATURE" \
            -H "x-teg-timestamp: $TIMESTAMP" \
            -H "x-teg-correlation-id: $CORRELATION_ID" \
            -H "x-app-trace-id: $TRACE_ID" \
            -H "x-consumer-service: liskov" \
            -H "User-Agent: Liskov/$VERSION_NAME($VERSION_CODE) (android)" \
            -H "x-teg-client-name: Economist-Android" \
            -H "x-teg-client-os: Android" \
            -H "x-teg-client-version: $VERSION_NAME" \
            -H "X-Economist-Consumer: TheEconomist-Liskov-android-${VERSION_NAME}_${VERSION_CODE}" \
            -o new.json \
            -w "%{http_code}")

          echo "HTTP status: $HTTP_CODE"

          if [ "$HTTP_CODE" != "200" ]; then
            echo "GraphQL request failed:"
            cat new.json
            exit 1
          fi 

      - name: Verify new.json
        run: |
          test -s new.json || {
            echo "Download failed or file is empty!"
            exit 1
          }

          jq empty new.json || {
            echo "Downloaded file is not valid JSON!"
            cat new.json
            exit 1
          }

          jq -e '.data.searchEditions.edges' new.json > /dev/null || {
            echo "GraphQL response does not contain expected data!"
            cat new.json
            exit 1
          }

      - name: Ensure merged file exists or create fallback
        run: |
          if [ ! -f "$MERGED_FILE_NAME" ]; then
            echo '{"data":{"searchEditions":{"edges":[]}}}' > "$MERGED_FILE_NAME"
            echo "Created new fallback file $MERGED_FILE_NAME"
          fi

      - name: Merge JSON and remove duplicates by node.id
        run: |
          jq -s -c '
            {
              data: {
                searchEditions: {
                  edges: (
                    map(.data.searchEditions.edges) | add
                    | map(select(.node.issueDate | startswith(env.CURRENT_YEAR)))
                    | unique_by(.node.issueDate)
                    | reverse
                  )
                }
              }
            }
          ' new.json "$MERGED_FILE_NAME" > temp.json && mv -f temp.json "$MERGED_FILE_NAME"


      - name: Commit and push merged.json (optional)
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "$MERGED_FILE_NAME"
          git commit -m "Update json file" || echo "No changes to commit"
          git push
